version: "3"
services: 
  sonarqube:
    image: sonarqube:7.1-alpine
    container_name: sonarqube
    ports:
      - "9000:9000"
      - "9092:9092"
    environment:
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
      - SONARQUBE_JDBC_URL="jdbc:postgresql://postgres:5432/sonar"
    volumes:
      - /srv/sonarqube/data:/opt/sonarqube/data
    depends_on:
      - postgres
    networks:
      - ci
      
  postgres:
    images: postgres:11-alpine
    container_name: postgres
    environment: 
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - /srv/postgres/data:/var/lib/postgresql/data
    networks:
      - ci

networks:
  ci: