version: "3"
services: 
  jenkins:
    image: apemon/jenkins-master:latest
    environment:
      - JAVA_OPTS="-Xmx2048m"
    ports:
      - "10080:8080"
      - "50000:50000"
    volumes:
      - /srv/jenkins/home:/var/jenkins_home
      - /srv/jenkins/log:/var/log/jenkins
      - /var/run/docker.sock:/var/run/docker.sock

